import { Drink } from './drink';

export const DRINKS: Drink[] = [
    {   id: 1, 
        name: 'Old Fashioned', 
        ingredients: 'whiskey, bitters, sugar cube, water',
        identifiers: 'sweet, bitter',
        description: 'Good ole fashioned fun!', 
        image: './assets/old_fashioned.jpg',
        rating: 3   },
    {   id: 2, 
        name: 'Juan Collins',
        ingredients: 'tequila, lemon juice, agave nectar, club soda',
        identifiers: 'sweet, sour',
        description: 'Mexican Tom Collins',
        image: './assets/juan_collins.png',
        rating: 4   },
    {   id: 3, 
        name: 'Japanese Slipper',
        ingredients: 'midori, cointreau, lemon juice',
        identifiers: 'sour',
        description: 'Not really Japanese',
        image: './assets/japanese_slipper.png',
        rating: 2   },
    {   id: 4, 
        name: 'Gimlet',
        ingredients: 'gin, simple syrup, lime juice',
        identifiers: 'sweet, sour',
        description: 'Just gin and lime',
        image: './assets/gimlet',
        rating: 5   },
    {   id: 5, 
        name: 'Salty Dog',
        ingredients: 'gin, grapefruit juice',
        identifiers: 'sour',
        description: 'One salt away from a greyhound',
        image: './assets/salty_dog.jpg',
        rating: 4   },
    {   id: 6, 
        name: 'Tom Collins',
        ingredients: 'gin, lemon juice, sugar syrup, carbonated water',
        identifiers: 'sweet, sour',
        description: 'Gin and sparkling lemonade',
        image: './assets/tom_collins.jpg',
        rating: 5   },
    {   id: 7, 
        name: 'Yellow Bird',
        ingredients: 'white rum, galliano, triple sec, lime juice',
        identifiers: 'sweet, sour',
        description: 'A classic Caribbean drink',
        image: './assets/yellow_bird.png',
        rating: 4   },
    {   id: 8, 
        name: 'Cuba Libre',
        ingredients: 'cola, light rum, lime juice',
        identifiers: 'sweet, sour',
        description: 'Basically a rum and coke',
        image: './assets/cuba_libre.jpg',
        rating: 2   },
    {   id: 9, 
        name: 'Godmother',
        ingredients: 'vodka, amaretto',
        identifiers: 'sweet',
        description: 'Nicer than the Godfather',
        image: './assets/godmother.png',
        rating: 1   },
    {   id: 10, 
        name: 'Tommy\'s Margarita',
        ingredients: 'tequila, lime juice, agave nectar',
        identifiers: 'sour',
        description: 'A man\'s margarita',
        image: './assets/tommys_margarita.png',
        rating: 5   }
];


